#import <Foundation/Foundation.h>
@class BerTag;

@interface EIDBerTags : NSObject
//EIDFile0201
+(BerTag *)ID_NUMBER;
+(BerTag *)CARD_NUMBER;
//EIDFile0202
+(BerTag *)FACIAL_IMAGE;
//EIDFile0203
+(BerTag *)ID_TYPE;
+(BerTag *)CARD_ISSUE_DATE;
+(BerTag *)CARD_EXPIRY_DATE;
+(BerTag *)ARABIC_TITLE;
+(BerTag *)ARABIC_FULL_NAME;
+(BerTag *)ENGLISH_TITLE;
+(BerTag *)ENGLISH_FULL_NAME;
+(BerTag *)GENDER_CODE;
+(BerTag *)ARABIC_NATIONALITY_CODE;
+(BerTag *)ENGLISH_NATIONALITY_CODE;
+(BerTag *)ENGLISH_NATIONALITY;
+(BerTag *)DATE_OF_BIRTH;
+(BerTag *)ARABIC_MOTHER_FIRST_NAME;
+(BerTag *)ENGLISH_MOTHER_FIRST_NAME;
+(BerTag *)PLACE_OF_BIRTH;
+(BerTag *)ARABIC_PLACE_OF_BIRTH;
//TODO: Sponsor Type
//TODO: Sponsor Number
//TODO: Sponsor Name
//TODO: Residency Type
//TODO: Residency Number
//TODO: Residency Expiry-Date
//TODO: Card Number
//TODO: Occupation
//TODO: Maritial Status
//We don't need: Family ID/Husband IDN
//TODO: English_Nationality_Code parsing along to the spec.
//TODO: Gender_Code parsing along to the spec.

//EIDFile0205
+(BerTag *)OCCUPATION_CODE;
+(BerTag *)MARITIAL_STATUS_CODE;
+(BerTag *)HUSBAND_IDN;
+(BerTag *)SPONSOR_TYPE;
+(BerTag *)SPONSOR_NUMBER;
+(BerTag *)SPONSOR_NAME_ENGLISH;
+(BerTag *)SPONSOR_NAME_ARABIC;
+(BerTag *)RESIDENCY_TYPE;
+(BerTag *)RESIDENCY_NUMBER;
+(BerTag *)RESIDENCY_EXPIRY_DATE;
+(BerTag *)FAMILY_ID;
+(BerTag *)PASSPORT_NUMBER;
+(BerTag *)PASSPORT_COUNTRY_ARABIC;
+(BerTag *)PASSPORT_COUNTRY_ENGLISH;
+(BerTag *)PASSPORT_COUNTRY_CODE_ENGLISH;
+(BerTag *)PASSPORT_ISSUE_DATE;
+(BerTag *)PASSPORT_EXPIRY_DATE;
+(BerTag *)QUALIFICATION_LEVEL_DESCRIPTION_ARABIC;
+(BerTag *)QUALIFICATION_LEVEL_DESCRIPTION_ENGLISH;
+(BerTag *)DEGREE_DESCRIPTION_ARABIC;
+(BerTag *)DEGREE_DESCRIPTION_ENGLISH;
+(BerTag *)FIELD_OF_STUDY_ARABIC;
+(BerTag *)FIELD_OF_STUDY_ENGLISH;
+(BerTag *)DATE_OF_GRADUATION;
+(BerTag *)OCCUPATION_ARABIC;
+(BerTag *)OCCUPATION_ENGLISH;
+(BerTag *)OCCUPATION_TYPE_ARABIC;
+(BerTag *)OCCUPATION_TYPE_ENGLISH;
+(BerTag *)COMPANY_NAME_ARABIC;
+(BerTag *)COMPANY_NAME_ENGLISH;
+(BerTag *)MOTHER_FULL_NAME_ARABIC;
+(BerTag *)MOTHER_FULL_NAME_ENGLISH;
+(BerTag *)EMIRATE_DESCRIPTION_ENGLISH;
+(BerTag *)EMIRATE_DESCRIPTION_ARABIC;
+(BerTag *)CITY_DESCRIPTION_ENGLISH;
+(BerTag *)CITY_DESCRIPTION_ARABIC;
+(BerTag *)STREET_DESCRIPTION_ENGLISH;
+(BerTag *)STREET_DESCRIPTION_ARABIC;
+(BerTag *)AREA_DESCRIPTION_ENGLISH;
+(BerTag *)AREA_DESCRIPTION_ARABIC;
+(BerTag *)BUILDING_DESCRIPTION_ENGLISH;
+(BerTag *)BUILDING_DESCRIPTION_ARABIC;
+(BerTag *)PHONE;
+(BerTag *)MOBILE;
+(BerTag *)PO_BOX;
//EIDFILE02x07
+(BerTag *)SIGNATURE_IMAGE;
@end
